global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: webapp-monitor

rule_files:
- "django.rules.yml"

scrape_configs:
- job_name: "django"
  static_configs:
  - targets: ["webapp:8000"]
